channels:
  - conda-forge

dependencies:
  - python=3.10.14 # https://pyreadiness.org/3.10
  - uv=0.2.6
  - pip:
      - rpaframework==28.6.0 # https://rpaframework.org/releasenotes.html
      - robocorp==2.0.2 # https://pypi.org/project/robocorp

